site_name: angmar Notes
site_description: Reverse Engineering, Assembly, Systems Programming and Debugging Notes
site_url: https://skllcrshrs.github.io/notes-portal/

theme:
  name: material
  font: false
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Home: index.md
  - RE: re/index.md
  - RE4B: re4b/index.md
  - CSAPP: csapp/index.md
  - Modern x86: modern-x86/index.md
  - PBA: pba/index.md
  - Reversing: reversing/index.md
  - Radare2: radare2/index.md
